name: Auto Pre-release

on:
  push:
    branches:
      - release/*

env:
  BRANCH_NAME: ${{ github.ref_name }}
  GH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

jobs:
  run-build-on-bitrise:
    name: Pre-release
    runs-on: ubuntu-latest
    if: "github.actor != 'h-bot-mobile'"
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Install libraries and run linters and unit tests
        run: |
          yarn install
          # yarn typecheck
          # yarn lint
          # yarn test:unit

          echo ${{ github.actor }}
          echo ${{ github }}
